name: Update README

on:
  schedule:
    # cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
      - uses: jamesgeorge007/github-activity-readme@v0.3.6
        with:
           # Your GitHub username
           GH_USERNAME: manusebas # optional, default is ${{ github.repository_owner }}
           # Path to configuration file
           #CONFIG_FILE: # optional, default is ./.github/recent-activity.config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
